// <auto-generated />
using System;
using CommerceCore.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace CommerceCore.Persistence.Migrations
{
    [DbContext(typeof(CommerceCoreDbContext))]
    [Migration("20260817231403_AddProductTypes")]
    partial class AddProductTypes
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "ltree");
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("CommerceCore.Domain.Catalog.ProductTypes.AttributeDefinition", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("DataType")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("data_type");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("integer")
                        .HasColumnName("display_order");

                    b.Property<string>("EnforcementStatus")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("enforcement_status");

                    b.Property<bool>("IsDeprecated")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_deprecated");

                    b.Property<bool>("IsRequired")
                        .HasColumnType("boolean")
                        .HasColumnName("is_required");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("key");

                    b.Property<int?>("MaximumLength")
                        .HasColumnType("integer")
                        .HasColumnName("maximum_length");

                    b.Property<decimal?>("MaximumValue")
                        .HasPrecision(18, 4)
                        .HasColumnType("numeric(18,4)")
                        .HasColumnName("maximum_value");

                    b.Property<string>("MeasurementUnitFamily")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("measurement_unit_family");

                    b.Property<int?>("MinimumLength")
                        .HasColumnType("integer")
                        .HasColumnName("minimum_length");

                    b.Property<decimal?>("MinimumValue")
                        .HasPrecision(18, 4)
                        .HasColumnType("numeric(18,4)")
                        .HasColumnName("minimum_value");

                    b.Property<Guid>("ProductTypeId")
                        .HasColumnType("uuid")
                        .HasColumnName("product_type_id");

                    b.Property<string>("Scope")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("scope");

                    b.HasKey("Id");

                    b.HasIndex("ProductTypeId", "DisplayOrder")
                        .IsUnique()
                        .HasDatabaseName("ux_attribute_definitions_product_type_display_order");

                    b.HasIndex("ProductTypeId", "Key")
                        .IsUnique()
                        .HasDatabaseName("ux_attribute_definitions_product_type_key");

                    b.ToTable("attribute_definitions", "catalog");
                });

            modelBuilder.Entity("CommerceCore.Domain.Catalog.ProductTypes.AttributeOption", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("AttributeDefinitionId")
                        .HasColumnType("uuid")
                        .HasColumnName("attribute_definition_id");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("code");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("integer")
                        .HasColumnName("display_order");

                    b.Property<bool>("IsDeprecated")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_deprecated");

                    b.HasKey("Id");

                    b.HasIndex("AttributeDefinitionId", "Code")
                        .IsUnique()
                        .HasDatabaseName("ux_attribute_options_definition_code");

                    b.HasIndex("AttributeDefinitionId", "DisplayOrder")
                        .IsUnique()
                        .HasDatabaseName("ux_attribute_options_definition_display_order");

                    b.ToTable("attribute_options", "catalog");
                });

            modelBuilder.Entity("CommerceCore.Domain.Catalog.ProductTypes.ProductType", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("code");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("created_by");

                    b.Property<bool>("IsAssignable")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_assignable");

                    b.Property<Guid?>("ParentProductTypeId")
                        .HasColumnType("uuid")
                        .HasColumnName("parent_product_type_id");

                    b.Property<long>("SchemaVersion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasDefaultValue(0L)
                        .HasColumnName("schema_version");

                    b.Property<DateTimeOffset?>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at_utc");

                    b.Property<string>("UpdatedBy")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("updated_by");

                    b.Property<string>("path")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("ltree")
                        .HasColumnName("path");

                    b.Property<uint>("xmin")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique()
                        .HasDatabaseName("ux_product_types_code");

                    b.HasIndex("ParentProductTypeId")
                        .HasDatabaseName("ix_product_types_parent_product_type_id");

                    b.HasIndex("path")
                        .HasDatabaseName("ix_product_types_path_gist");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("path"), "gist");

                    b.ToTable("product_types", "catalog");
                });

            modelBuilder.Entity("CommerceCore.Domain.Catalog.Products.Product", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("created_by");

                    b.Property<DateTimeOffset?>("DeletedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at_utc");

                    b.Property<string>("DeletedBy")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("deleted_by");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_deleted");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("name");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("status");

                    b.Property<DateTimeOffset?>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at_utc");

                    b.Property<string>("UpdatedBy")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("updated_by");

                    b.Property<uint>("xmin")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id");

                    b.HasIndex("Status", "IsDeleted");

                    b.ToTable("products", "catalog");
                });

            modelBuilder.Entity("CommerceCore.Persistence.Outbox.OutboxMessage", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("AttemptCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("attempt_count");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("content");

                    b.Property<string>("LastError")
                        .HasColumnType("text")
                        .HasColumnName("last_error");

                    b.Property<DateTimeOffset>("OccurredOnUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("occurred_on_utc");

                    b.Property<DateTimeOffset?>("ProcessedOnUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("processed_on_utc");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("type");

                    b.HasKey("Id");

                    b.HasIndex("OccurredOnUtc")
                        .HasDatabaseName("ix_messages_pending_occurred_on_utc")
                        .HasFilter("\"processed_on_utc\" IS NULL");

                    b.ToTable("messages", "outbox");
                });

            modelBuilder.Entity("CommerceCore.Domain.Catalog.ProductTypes.AttributeDefinition", b =>
                {
                    b.HasOne("CommerceCore.Domain.Catalog.ProductTypes.ProductType", null)
                        .WithMany("AttributeDefinitions")
                        .HasForeignKey("ProductTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_attribute_definitions_product_type");
                });

            modelBuilder.Entity("CommerceCore.Domain.Catalog.ProductTypes.AttributeOption", b =>
                {
                    b.HasOne("CommerceCore.Domain.Catalog.ProductTypes.AttributeDefinition", null)
                        .WithMany("Options")
                        .HasForeignKey("AttributeDefinitionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_attribute_options_attribute_definition");
                });

            modelBuilder.Entity("CommerceCore.Domain.Catalog.ProductTypes.ProductType", b =>
                {
                    b.HasOne("CommerceCore.Domain.Catalog.ProductTypes.ProductType", null)
                        .WithMany()
                        .HasForeignKey("ParentProductTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_product_types_parent_product_type");
                });

            modelBuilder.Entity("CommerceCore.Domain.Catalog.Products.Product", b =>
                {
                    b.OwnsOne("CommerceCore.Domain.Common.ValueObjects.Money", "Price", b1 =>
                        {
                            b1.Property<Guid>("ProductId")
                                .HasColumnType("uuid");

                            b1.Property<decimal>("Amount")
                                .HasPrecision(18, 4)
                                .HasColumnType("numeric(18,4)")
                                .HasColumnName("price_amount");

                            b1.Property<string>("Currency")
                                .IsRequired()
                                .HasMaxLength(3)
                                .HasColumnType("character varying(3)")
                                .HasColumnName("price_currency");

                            b1.HasKey("ProductId");

                            b1.HasIndex("Currency", "Amount")
                                .HasDatabaseName("ix_products_price_currency_amount");

                            b1.ToTable("products", "catalog");

                            b1.WithOwner()
                                .HasForeignKey("ProductId");
                        });

                    b.Navigation("Price")
                        .IsRequired();
                });

            modelBuilder.Entity("CommerceCore.Domain.Catalog.ProductTypes.AttributeDefinition", b =>
                {
                    b.Navigation("Options");
                });

            modelBuilder.Entity("CommerceCore.Domain.Catalog.ProductTypes.ProductType", b =>
                {
                    b.Navigation("AttributeDefinitions");
                });
#pragma warning restore 612, 618
        }
    }
}
