// <auto-generated />
using System;
using CommerceCore.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace CommerceCore.Persistence.Migrations
{
    [DbContext(typeof(CommerceCoreDbContext))]
    partial class CommerceCoreDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "ltree");
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("CommerceCore.Domain.Catalog.ProductTypes.AttributeDefinition", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("DataType")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("data_type");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("integer")
                        .HasColumnName("display_order");

                    b.Property<string>("EnforcementStatus")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("enforcement_status");

                    b.Property<bool>("IsDeprecated")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_deprecated");

                    b.Property<bool>("IsRequired")
                        .HasColumnType("boolean")
                        .HasColumnName("is_required");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("key");

                    b.Property<int?>("MaximumLength")
                        .HasColumnType("integer")
                        .HasColumnName("maximum_length");

                    b.Property<decimal?>("MaximumValue")
                        .HasPrecision(18, 4)
                        .HasColumnType("numeric(18,4)")
                        .HasColumnName("maximum_value");

                    b.Property<string>("MeasurementUnitFamily")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("measurement_unit_family");

                    b.Property<int?>("MinimumLength")
                        .HasColumnType("integer")
                        .HasColumnName("minimum_length");

                    b.Property<decimal?>("MinimumValue")
                        .HasPrecision(18, 4)
                        .HasColumnType("numeric(18,4)")
                        .HasColumnName("minimum_value");

                    b.Property<Guid>("ProductTypeId")
                        .HasColumnType("uuid")
                        .HasColumnName("product_type_id");

                    b.Property<string>("Scope")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("scope");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.HasKey("Id");

                    b.HasAlternateKey("TenantId", "Id")
                        .HasName("ux_attribute_definitions_tenant_id_id");

                    b.HasIndex("ProductTypeId");

                    b.HasIndex("TenantId", "ProductTypeId", "DisplayOrder")
                        .IsUnique()
                        .HasDatabaseName("ux_attribute_definitions_tenant_product_type_display_order");

                    b.HasIndex("TenantId", "ProductTypeId", "Key")
                        .IsUnique()
                        .HasDatabaseName("ux_attribute_definitions_tenant_product_type_key");

                    b.ToTable("attribute_definitions", "catalog");
                });

            modelBuilder.Entity("CommerceCore.Domain.Catalog.ProductTypes.AttributeOption", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("AttributeDefinitionId")
                        .HasColumnType("uuid")
                        .HasColumnName("attribute_definition_id");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("code");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("integer")
                        .HasColumnName("display_order");

                    b.Property<bool>("IsDeprecated")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_deprecated");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.HasKey("Id");

                    b.HasAlternateKey("TenantId", "Id")
                        .HasName("ux_attribute_options_tenant_id_id");

                    b.HasIndex("TenantId", "AttributeDefinitionId", "Code")
                        .IsUnique()
                        .HasDatabaseName("ux_attribute_options_tenant_definition_code");

                    b.HasIndex("TenantId", "AttributeDefinitionId", "DisplayOrder")
                        .IsUnique()
                        .HasDatabaseName("ux_attribute_options_tenant_definition_display_order");

                    b.ToTable("attribute_options", "catalog");
                });

            modelBuilder.Entity("CommerceCore.Domain.Catalog.ProductTypes.ProductType", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("code");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("created_by");

                    b.Property<bool>("IsAssignable")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_assignable");

                    b.Property<long>("OwnSchemaVersion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasDefaultValue(0L)
                        .HasColumnName("own_schema_version");

                    b.Property<Guid?>("ParentProductTypeId")
                        .HasColumnType("uuid")
                        .HasColumnName("parent_product_type_id");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<DateTimeOffset?>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at_utc");

                    b.Property<string>("UpdatedBy")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("updated_by");

                    b.Property<string>("path")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("ltree")
                        .HasColumnName("path");

                    b.Property<uint>("xmin")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id");

                    b.HasAlternateKey("TenantId", "Id")
                        .HasName("ux_product_types_tenant_id_id");

                    b.HasIndex("ParentProductTypeId");

                    b.HasIndex("path")
                        .HasDatabaseName("ix_product_types_path_gist");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("path"), "gist");

                    b.HasIndex("TenantId", "Code")
                        .IsUnique()
                        .HasDatabaseName("ux_product_types_tenant_code");

                    b.HasIndex("TenantId", "ParentProductTypeId")
                        .HasDatabaseName("ix_product_types_tenant_parent_product_type_id");

                    b.ToTable("product_types", "catalog");
                });

            modelBuilder.Entity("CommerceCore.Domain.Catalog.Products.Product", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("created_by");

                    b.Property<DateTimeOffset?>("DeletedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at_utc");

                    b.Property<string>("DeletedBy")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("deleted_by");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_deleted");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("name");

                    b.Property<Guid>("ProductTypeId")
                        .HasColumnType("uuid")
                        .HasColumnName("product_type_id");

                    b.Property<string>("Specifications")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("jsonb")
                        .HasColumnName("specifications")
                        .HasDefaultValueSql("'{}'::jsonb");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("status");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<DateTimeOffset?>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at_utc");

                    b.Property<string>("UpdatedBy")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("updated_by");

                    b.Property<long>("ValidatedAgainstVersion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasDefaultValue(0L)
                        .HasColumnName("validated_against_version");

                    b.Property<uint>("xmin")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id");

                    b.HasAlternateKey("TenantId", "Id")
                        .HasName("ux_products_tenant_id_id");

                    b.HasIndex("TenantId", "ProductTypeId")
                        .HasDatabaseName("ix_products_tenant_not_deleted_product_type_id")
                        .HasFilter("\"is_deleted\" = FALSE");

                    b.HasIndex("TenantId", "Status", "IsDeleted")
                        .HasDatabaseName("ix_products_tenant_status_is_deleted");

                    b.ToTable("products", "catalog");
                });

            modelBuilder.Entity("CommerceCore.Domain.Catalog.Products.ProductVariant", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<bool>("IsDefault")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_default");

                    b.Property<string>("Options")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("jsonb")
                        .HasColumnName("options")
                        .HasDefaultValueSql("'{}'::jsonb");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("uuid")
                        .HasColumnName("product_id");

                    b.Property<string>("Sku")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("sku");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("status");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<uint>("xmin")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id");

                    b.HasAlternateKey("TenantId", "Id")
                        .HasName("ux_product_variants_tenant_id_id");

                    b.HasIndex("TenantId", "ProductId")
                        .IsUnique()
                        .HasDatabaseName("ux_product_variants_tenant_default_per_product")
                        .HasFilter("\"is_default\" = TRUE");

                    b.HasIndex("TenantId", "Sku")
                        .IsUnique()
                        .HasDatabaseName("ux_product_variants_tenant_sku");

                    b.HasIndex("TenantId", "ProductId", "Options")
                        .IsUnique()
                        .HasDatabaseName("ux_product_variants_tenant_product_id_options");

                    b.ToTable("product_variants", "catalog");
                });

            modelBuilder.Entity("CommerceCore.Persistence.Outbox.OutboxMessage", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("AttemptCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("attempt_count");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("content");

                    b.Property<string>("LastError")
                        .HasColumnType("text")
                        .HasColumnName("last_error");

                    b.Property<DateTimeOffset>("OccurredOnUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("occurred_on_utc");

                    b.Property<DateTimeOffset?>("ProcessedOnUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("processed_on_utc");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("type");

                    b.HasKey("Id");

                    b.HasIndex("TenantId", "OccurredOnUtc")
                        .HasDatabaseName("ix_outbox_messages_tenant_pending_occurred_on_utc")
                        .HasFilter("\"processed_on_utc\" IS NULL");

                    b.ToTable("messages", "outbox");
                });

            modelBuilder.Entity("CommerceCore.Persistence.ProductTypes.ProductTypeEffectiveSchema", b =>
                {
                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<Guid>("ProductTypeId")
                        .HasColumnType("uuid")
                        .HasColumnName("product_type_id");

                    b.Property<long>("EffectiveSchemaVersion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasDefaultValue(0L)
                        .HasColumnName("effective_schema_version");

                    b.Property<string>("Schema")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("jsonb")
                        .HasColumnName("schema")
                        .HasDefaultValueSql("'{}'::jsonb");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at_utc")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.HasKey("TenantId", "ProductTypeId");

                    b.ToTable("product_type_effective_schema", "catalog");
                });

            modelBuilder.Entity("CommerceCore.Platform.ControlPlane.Entities.Storefront", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("DefaultLocale")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("default_locale");

                    b.Property<string>("HostName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("host_name");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<string>("MarketCode")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("market_code");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.HasKey("Id");

                    b.HasIndex("HostName")
                        .IsUnique()
                        .HasDatabaseName("ix_platform_storefronts_host_name");

                    b.HasIndex("TenantId");

                    b.ToTable("storefronts", "platform");
                });

            modelBuilder.Entity("CommerceCore.Platform.ControlPlane.Entities.Tenant", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("slug");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("status");

                    b.HasKey("Id");

                    b.HasIndex("Slug")
                        .IsUnique()
                        .HasDatabaseName("ix_platform_tenants_slug");

                    b.ToTable("tenants", "platform");
                });

            modelBuilder.Entity("CommerceCore.Platform.ControlPlane.Entities.TenantMembership", b =>
                {
                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<string>("UserSubject")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("user_subject");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("role");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("status");

                    b.HasKey("TenantId", "UserSubject");

                    b.HasIndex("UserSubject")
                        .HasDatabaseName("ix_platform_tenant_memberships_user_subject");

                    b.ToTable("tenant_memberships", "platform");
                });

            modelBuilder.Entity("CommerceCore.Domain.Catalog.ProductTypes.AttributeDefinition", b =>
                {
                    b.HasOne("CommerceCore.Domain.Catalog.ProductTypes.ProductType", null)
                        .WithMany("AttributeDefinitions")
                        .HasForeignKey("ProductTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_attribute_definitions_product_type");
                });

            modelBuilder.Entity("CommerceCore.Domain.Catalog.ProductTypes.AttributeOption", b =>
                {
                    b.HasOne("CommerceCore.Domain.Catalog.ProductTypes.AttributeDefinition", null)
                        .WithMany("Options")
                        .HasForeignKey("TenantId", "AttributeDefinitionId")
                        .HasPrincipalKey("TenantId", "Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_attribute_options_attribute_definition");
                });

            modelBuilder.Entity("CommerceCore.Domain.Catalog.ProductTypes.ProductType", b =>
                {
                    b.HasOne("CommerceCore.Domain.Catalog.ProductTypes.ProductType", null)
                        .WithMany()
                        .HasForeignKey("ParentProductTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_product_types_parent_product_type");
                });

            modelBuilder.Entity("CommerceCore.Domain.Catalog.Products.Product", b =>
                {
                    b.HasOne("CommerceCore.Domain.Catalog.ProductTypes.ProductType", null)
                        .WithMany()
                        .HasForeignKey("TenantId", "ProductTypeId")
                        .HasPrincipalKey("TenantId", "Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_products_product_type");

                    b.OwnsOne("CommerceCore.Domain.Common.ValueObjects.Money", "Price", b1 =>
                        {
                            b1.Property<Guid>("ProductId")
                                .HasColumnType("uuid");

                            b1.Property<decimal>("Amount")
                                .HasPrecision(18, 4)
                                .HasColumnType("numeric(18,4)")
                                .HasColumnName("price_amount");

                            b1.Property<string>("Currency")
                                .IsRequired()
                                .HasMaxLength(3)
                                .HasColumnType("character varying(3)")
                                .HasColumnName("price_currency");

                            b1.HasKey("ProductId");

                            b1.HasIndex("Currency", "Amount")
                                .HasDatabaseName("ix_products_price_currency_amount");

                            b1.ToTable("products", "catalog");

                            b1.WithOwner()
                                .HasForeignKey("ProductId");
                        });

                    b.Navigation("Price")
                        .IsRequired();
                });

            modelBuilder.Entity("CommerceCore.Domain.Catalog.Products.ProductVariant", b =>
                {
                    b.HasOne("CommerceCore.Domain.Catalog.Products.Product", null)
                        .WithMany("Variants")
                        .HasForeignKey("TenantId", "ProductId")
                        .HasPrincipalKey("TenantId", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_product_variants_product");

                    b.OwnsOne("CommerceCore.Domain.Common.ValueObjects.Money", "Price", b1 =>
                        {
                            b1.Property<Guid>("ProductVariantId")
                                .HasColumnType("uuid");

                            b1.Property<decimal>("Amount")
                                .HasPrecision(18, 4)
                                .HasColumnType("numeric(18,4)")
                                .HasColumnName("price_amount");

                            b1.Property<string>("Currency")
                                .IsRequired()
                                .HasMaxLength(3)
                                .HasColumnType("character varying(3)")
                                .HasColumnName("price_currency");

                            b1.HasKey("ProductVariantId");

                            b1.HasIndex("Currency", "Amount")
                                .HasDatabaseName("ix_product_variants_price_currency_amount");

                            b1.ToTable("product_variants", "catalog");

                            b1.WithOwner()
                                .HasForeignKey("ProductVariantId");
                        });

                    b.Navigation("Price")
                        .IsRequired();
                });

            modelBuilder.Entity("CommerceCore.Persistence.ProductTypes.ProductTypeEffectiveSchema", b =>
                {
                    b.HasOne("CommerceCore.Domain.Catalog.ProductTypes.ProductType", null)
                        .WithOne()
                        .HasForeignKey("CommerceCore.Persistence.ProductTypes.ProductTypeEffectiveSchema", "TenantId", "ProductTypeId")
                        .HasPrincipalKey("CommerceCore.Domain.Catalog.ProductTypes.ProductType", "TenantId", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_product_type_effective_schema_product_type");
                });

            modelBuilder.Entity("CommerceCore.Platform.ControlPlane.Entities.Storefront", b =>
                {
                    b.HasOne("CommerceCore.Platform.ControlPlane.Entities.Tenant", null)
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_storefronts_tenant");
                });

            modelBuilder.Entity("CommerceCore.Platform.ControlPlane.Entities.TenantMembership", b =>
                {
                    b.HasOne("CommerceCore.Platform.ControlPlane.Entities.Tenant", null)
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_tenant_memberships_tenant");
                });

            modelBuilder.Entity("CommerceCore.Domain.Catalog.ProductTypes.AttributeDefinition", b =>
                {
                    b.Navigation("Options");
                });

            modelBuilder.Entity("CommerceCore.Domain.Catalog.ProductTypes.ProductType", b =>
                {
                    b.Navigation("AttributeDefinitions");
                });

            modelBuilder.Entity("CommerceCore.Domain.Catalog.Products.Product", b =>
                {
                    b.Navigation("Variants");
                });
#pragma warning restore 612, 618
        }
    }
}
