<Project Sdk="Microsoft.NET.Sdk.Web">

	<PropertyGroup>
		<TargetFramework>net10.0</TargetFramework>
		<Nullable>enable</Nullable>
		<ImplicitUsings>enable</ImplicitUsings>
	  <UserSecretsId>627ff576-5e1a-419e-ad4f-c5038980b283</UserSecretsId>
  </PropertyGroup>

	<ItemGroup>
		<PackageReference Include="Mediator.Abstractions" Version="3.0.2" />
		<PackageReference Include="Mediator.SourceGenerator" Version="3.0.2">
			<PrivateAssets>all</PrivateAssets>
			<IncludeAssets>runtime; build; native; contentfiles; analyzers</IncludeAssets>
		</PackageReference>
		<PackageReference Include="Microsoft.AspNetCore.OpenApi" Version="10.0.11" />
		<PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="10.0.11">
		  <PrivateAssets>all</PrivateAssets>
		  <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
		</PackageReference>
		<PackageReference Include="OpenTelemetry.Exporter.OpenTelemetryProtocol" Version="1.18.0" />
		<PackageReference Include="OpenTelemetry.Extensions.Hosting" Version="1.18.0" />
		<PackageReference Include="OpenTelemetry.Instrumentation.AspNetCore" Version="1.18.0" />
		<PackageReference Include="OpenTelemetry.Instrumentation.Http" Version="1.18.0" />
		<PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" Version="10.0.11" />
	</ItemGroup>

	<ItemGroup>
		<ProjectReference Include="..\..\Core\CommerceCore.Application\CommerceCore.Application.csproj" />
		<ProjectReference Include="..\..\Infrastructure\CommerceCore.Infrastructure\CommerceCore.Infrastructure.csproj" />
		<ProjectReference Include="..\..\Infrastructure\CommerceCore.Persistence\CommerceCore.Persistence.csproj" />
		<ProjectReference Include="..\..\Modules\Catalog\CommerceCore.Modules.Catalog.Domain\CommerceCore.Modules.Catalog.Domain.csproj" />
		<ProjectReference Include="..\..\Modules\Catalog\CommerceCore.Modules.Catalog.Application\CommerceCore.Modules.Catalog.Application.csproj" />
		<ProjectReference Include="..\..\Platform\CommerceCore.Platform.Contracts\CommerceCore.Platform.Contracts.csproj" />
		<ProjectReference Include="..\..\Platform\CommerceCore.Platform.ControlPlane\CommerceCore.Platform.ControlPlane.csproj" />
		<ProjectReference Include="..\..\Platform\CommerceCore.Platform.Identity\CommerceCore.Platform.Identity.csproj" />
	</ItemGroup>

</Project>